/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
