/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomInput: typeof import('./src/components/customInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GoBack: typeof import('./src/components/goBack.vue')['default']
    ImgDialog: typeof import('./src/components/message/imgDialog.vue')['default']
    Map: typeof import('./src/components/message/map.vue')['default']
    MessInput: typeof import('./src/components/message/messInput.vue')['default']
    MessMain: typeof import('./src/components/message/messMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/message/swiper.vue')['default']
    UpImg: typeof import('./src/components/upImg.vue')['default']
    VisibUpImg: typeof import('./src/components/visibUpImg.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
